// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMy9pHiskzcsuOYM0oASJgPbk9Mmz3brg',
    appId: '1:403552634022:web:e48b5492ecace49ed5a067',
    messagingSenderId: '403552634022',
    projectId: 'finance-app-e043d',
    authDomain: 'finance-app-e043d.firebaseapp.com',
    storageBucket: 'finance-app-e043d.appspot.com',
    measurementId: 'G-KH90K9B4Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJeTCABV_rXirhlZLvk9UNd8Gtd_1DYo',
    appId: '1:403552634022:android:9de7fe07e1160f99d5a067',
    messagingSenderId: '403552634022',
    projectId: 'finance-app-e043d',
    storageBucket: 'finance-app-e043d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZdsGwe2nSVEefYCDgymi_M_Wx6F4xRE',
    appId: '1:403552634022:ios:319240a20176b48cd5a067',
    messagingSenderId: '403552634022',
    projectId: 'finance-app-e043d',
    storageBucket: 'finance-app-e043d.appspot.com',
    iosBundleId: 'com.example.finances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZdsGwe2nSVEefYCDgymi_M_Wx6F4xRE',
    appId: '1:403552634022:ios:319240a20176b48cd5a067',
    messagingSenderId: '403552634022',
    projectId: 'finance-app-e043d',
    storageBucket: 'finance-app-e043d.appspot.com',
    iosBundleId: 'com.example.finances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMy9pHiskzcsuOYM0oASJgPbk9Mmz3brg',
    appId: '1:403552634022:web:bd1a14df273c5177d5a067',
    messagingSenderId: '403552634022',
    projectId: 'finance-app-e043d',
    authDomain: 'finance-app-e043d.firebaseapp.com',
    storageBucket: 'finance-app-e043d.appspot.com',
    measurementId: 'G-7SK4HTX13X',
  );

}